//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltKategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AltKategori()
        {
            this.Uruns = new HashSet<Urun>();
        }
    
        public int altKatID { get; set; }
        public string altKatAdi { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string altKatResim { get; set; }
        public Nullable<bool> altKatDurum { get; set; }
        public Nullable<int> kategoriID { get; set; }
        public Nullable<int> altKatsira { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urun> Uruns { get; set; }
    }
}
