//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bildirim
    {
        public int bildirimID { get; set; }
        public string bildirimTur { get; set; }
        public Nullable<bool> bildirimDurum { get; set; }
        public Nullable<int> masaID { get; set; }
        public System.DateTime bildirimDate { get; set; }
        public Nullable<bool> isChecked { get; set; }
    
        public virtual Masa Masa { get; set; }
    }
}
