//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarouselTwo
    {
        public int reklamtwoID { get; set; }
        public string reklamtwoHeader { get; set; }
        public string reklamtwoResim { get; set; }
        public string reklamtwoAciklamaHeader { get; set; }
        public string reklamtwoAciklama { get; set; }
        public string reklamtwoSira { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
