//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarouselOne
    {
        public int reklamID { get; set; }
        public string reklamHeader { get; set; }
        public string reklamResim { get; set; }
        public string reklamAciklamaHeader { get; set; }
        public string reklamAciklama { get; set; }
        public string reklamSira { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
