//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public IEnumerable<CartItem> cartlar { get; set; }
        
        public IEnumerable<CartItem> cartt { get; set; }
        public int cartItemID { get; set; }
        public Nullable<int> urunID { get; set; }
        public int miktar { get; set; }
        public decimal fiyat { get; set; }
        public Nullable<System.DateTime> zaman { get; set; }
        public Nullable<int> masaID { get; set; }
        public string odemeTur { get; set; }
        public Nullable<int> cartNo { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> onay { get; set; }
        public Nullable<bool> siparisonay { get; set; }
        public Nullable<int> urunSizeID { get; set; }
        public string urunMesaj { get; set; }
        public Nullable<int> extraUrunID { get; set; }
        public string extraUrunAdi { get; set; }
        public Nullable<decimal> urunYeniFiyat { get; set; }
    
        public virtual Masa Masa { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
