//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masa()
        {
            this.Bildirims = new HashSet<Bildirim>();
            this.CartItems = new HashSet<CartItem>();
            this.MusteriTaleps = new HashSet<MusteriTalep>();
        }
    
        public int masaID { get; set; }
        public string masaNo { get; set; }
        public Nullable<int> masaKat { get; set; }
        public string qrHash { get; set; }
        public string qrUrl { get; set; }
        public string qrFoto { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> masaKatID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bildirim> Bildirims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual User User { get; set; }
        public virtual masaKategori masaKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriTalep> MusteriTaleps { get; set; }
    }
}
