//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ibernsof_RestoranEntities : DbContext
    {
        public ibernsof_RestoranEntities()
            : base("name=ibernsof_RestoranEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AltKategori> AltKategoris { get; set; }
        public virtual DbSet<Bildirim> Bildirims { get; set; }
        public virtual DbSet<CarouselOne> CarouselOnes { get; set; }
        public virtual DbSet<CarouselTwo> CarouselTwoes { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<ExtraUrun> ExtraUruns { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Masa> Masas { get; set; }
        public virtual DbSet<SizeProduct> SizeProducts { get; set; }
        public virtual DbSet<Teklif> Teklifs { get; set; }
        public virtual DbSet<Urun> Uruns { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Yetki> Yetkis { get; set; }
        public virtual DbSet<masaKategori> masaKategoris { get; set; }
        public virtual DbSet<AdminAyar> AdminAyars { get; set; }
        public virtual DbSet<MusteriIstek> MusteriIsteks { get; set; }
        public virtual DbSet<MusteriTalep> MusteriTaleps { get; set; }
        public virtual DbSet<WebAyar> WebAyars { get; set; }
    }
}
