//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTalep
    {
        public int talepID { get; set; }
        public Nullable<int> musteriIstekID { get; set; }
        public Nullable<int> masaID { get; set; }
    
        public virtual Masa Masa { get; set; }
        public virtual MusteriIstek MusteriIstek { get; set; }
    }
}
