//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.CartItems = new HashSet<CartItem>();
            this.ExtraUruns = new HashSet<ExtraUrun>();
            this.SizeProducts = new HashSet<SizeProduct>();
        }

        public IEnumerable<Urun> singleurun { get; set; }
        public IEnumerable<SizeProduct> sizeurun { get; set; }
        public IEnumerable<ExtraUrun> extraurunler { get; set; }
        public int urunID { get; set; }
        public string urunAd { get; set; }
        public decimal urunFiyat { get; set; }
        public string urunResim { get; set; }
        public Nullable<int> altKatID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> userID { get; set; }
        public string urunAciklama { get; set; }
        public Nullable<int> urunMiktar { get; set; }
        public int urunStok { get; set; }
    
        public virtual AltKategori AltKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraUrun> ExtraUruns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SizeProduct> SizeProducts { get; set; }
        public virtual User User { get; set; }
    }
}
