//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ibernsof_Restoran.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebAyar
    {
        public int webAyarID { get; set; }
        public string title { get; set; }
        public string logo { get; set; }
        public string footerTitle { get; set; }
        public string ayarFacebook { get; set; }
        public string ayarInstagram { get; set; }
        public string ayarLinkedIn { get; set; }
        public string ayarGoogle { get; set; }
        public string ayarYoutube { get; set; }
    }
}
